# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Desktop\malcious URL\url_help1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication
import sys


class detection_help(QDialog):
    def __init__(self, *argv):  ###
        super().__init__(*argv)
        self.initUi()

    def initUi(self):
        self.resize(400, 315)
        self.setWindowTitle("帮助")
        self.label = QtWidgets.QLabel("URL检测操作指南", self)
        self.label.setGeometry(QtCore.QRect(120, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)

        self.groupBox = QtWidgets.QGroupBox("step 1.", self)
        self.groupBox.setGeometry(QtCore.QRect(40, 40, 311, 71))

        self.label_2 = QtWidgets.QLabel("输入URL，可以文本框输入，也可以\n由文件导入。", self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 261, 31))

        self.groupBox_2 = QtWidgets.QGroupBox("step 2.", self)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 110, 311, 51))

        self.label_3 = QtWidgets.QLabel("选择使用的算法模型", self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 251, 16))

        self.groupBox_4 = QtWidgets.QGroupBox("step 3.", self)
        self.groupBox_4.setGeometry(QtCore.QRect(40, 160, 311, 71))

        self.label_4 = QtWidgets.QLabel("点击“开始检测”，检测结果会输出\n在显示框内", self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(40, 20, 251, 41))

        self.groupBox_5 = QtWidgets.QGroupBox('step 4.', self)
        self.groupBox_5.setGeometry(QtCore.QRect(40, 230, 311, 71))

        self.label_5 = QtWidgets.QLabel("如果想要看看URL在特征提取时对应\n的灰度图像，可以输入URL点击“查看”，\n图像会显示在右侧", self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(40, 10, 261, 61))


if __name__ == "__main__":
    app = QApplication(sys.argv)
    Ui = detection_help()
    Ui.show()
    sys.exit(app.exec_())