# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Desktop\malcious URL\url_help2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication
import sys


class train_help(QDialog):
    def __init__(self, *argv):
        super().__init__(*argv)
        self.initUi()

    def initUi(self):
        self.setWindowTitle("帮助")
        self.resize(400, 315)
        self.label = QtWidgets.QLabel("模型训练操作指南", self)
        self.label.setGeometry(QtCore.QRect(120, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)

        self.groupBox = QtWidgets.QGroupBox("step 1.", self)
        self.groupBox.setGeometry(QtCore.QRect(40, 50, 311, 71))

        self.label_2 = QtWidgets.QLabel("选择合适的超参数", self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 261, 31))

        self.groupBox_2 = QtWidgets.QGroupBox("step 2.", self)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 140, 311, 51))

        self.label_3 = QtWidgets.QLabel("导入样本文件", self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 251, 16))

        self.groupBox_4 = QtWidgets.QGroupBox("step 3.", self)
        self.groupBox_4.setGeometry(QtCore.QRect(40, 210, 311, 71))

        self.label_4 = QtWidgets.QLabel("选择模型并开始训练", self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(40, 20, 251, 41))


if __name__ == "__main__":
    app = QApplication(sys.argv)
    ui = train_help()
    ui.show()
    sys.exit(app.exec_())